### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by Stinosko** [Jestemkiosk/py3rcon#1]
Hey,

I tried to install this module on my linux server by the command `pip3.7 install py3rcon` but i get a error during install. This is the output of pip3.7 install py3rcon -v, i tried with the --user flag but it result in the same output.
`$ pip3.7 install py3rcon -v
Created temporary directory: /tmp/pip-ephem-wheel-cache-jesb7s6i
Created temporary directory: /tmp/pip-req-tracker-6tu2p881
Created requirements tracker '/tmp/pip-req-tracker-6tu2p881'
Created temporary directory: /tmp/pip-install-zhwwf4xt
Collecting py3rcon
  1 location(s) to search for versions of py3rcon:
  * https://pypi.org/simple/py3rcon/
  Getting page https://pypi.org/simple/py3rcon/
  Looking up "https://pypi.org/simple/py3rcon/" in the cache
  Request header has "max_age" as 0, cache bypassed
  Starting new HTTPS connection (1): pypi.org:443
  https://pypi.org:443 "GET /simple/py3rcon/ HTTP/1.1" 304 0
  Analyzing links from page https://pypi.org/simple/py3rcon/
    Found link https://files.pythonhosted.org/packages/75/5b/d7ca2c3da6429a03da2c5a76084c6c1f817b564b4aa0d29af6dafdef8fd1/py3rcon-0.1.tar.gz#sha256=6aed5f5ee6da177539cdf31ebf3ea44cb5ee65b6f33fa3b82693feb49d3172e2 (from https://pypi.org/simple/py3rcon/), version: 0.1
    Found link https://files.pythonhosted.org/packages/6f/bf/3c63e3a48fe06ce681f8b84a4f4db4c433b3510f9fa99e6481bdb5af8186/py3rcon-0.1.1.tar.gz#sha256=cab539249f22507f9b5f44e8646d827102e181f971f095ecd166defddf6540a1 (from https://pypi.org/simple/py3rcon/), version: 0.1.1
    Found link https://files.pythonhosted.org/packages/96/02/94eb5efdec9641f23d0367802f3c25a2cf834544af0f33816e759d7e873c/py3rcon-0.1.2.tar.gz#sha256=fd0e9006293b05b332ceddd6fc7a7c3a94ec383b9fcab320ceedb90d905df904 (from https://pypi.org/simple/py3rcon/), version: 0.1.2
    Found link https://files.pythonhosted.org/packages/f3/2b/88d8fd286b51502f7ccd26aab15c48c4755cb27d58f93395b8a5d6d5fe66/py3rcon-0.1.3.tar.gz#sha256=f3c17a160126568655df74d39915b2895ad0ad04f8cf9f59f5db369efe7cf66f (from https://pypi.org/simple/py3rcon/), version: 0.1.3
    Found link https://files.pythonhosted.org/packages/64/7d/2fc275f45200cb67b2fad43e5678a85e3b6cb9858105ea1f734ab6f82858/py3rcon-0.1.4.tar.gz#sha256=563aefccfe62498eee51c8dace4e8993a8a5a3f9f8b2f549563f3a73da4ab51a (from https://pypi.org/simple/py3rcon/), version: 0.1.4
    Found link https://files.pythonhosted.org/packages/27/ad/c29c73b01b81ae7cbb43d100fd3706bc52b20158f2db35ed366fc21db092/py3rcon-0.1.5.tar.gz#sha256=d344f62ff624bf4c9e66e4e28199365a9d8115ea32edd5766f72cd30491fb8f4 (from https://pypi.org/simple/py3rcon/), version: 0.1.5
    Found link https://files.pythonhosted.org/packages/e6/84/671f1b25b3fa607a825984f1a1c25df8d04f814f33d592bb13ef34d2eb30/py3rcon-0.1.6.tar.gz#sha256=a8fba93d6e48d602b0b113878e0c0b5226b490f6be9f4a8c080fcaa98c3dbe8e (from https://pypi.org/simple/py3rcon/), version: 0.1.6
    Found link https://files.pythonhosted.org/packages/56/dd/a7381f1f7241650700efdf3b10400fc4a8ca0819900549f23c8446cedd9c/py3rcon-0.2.0.tar.gz#sha256=6b21e82b2520b4f009c30b0a8e55ef1be71ba52aeaf14ff56b4a85a1c5fb997e (from https://pypi.org/simple/py3rcon/), version: 0.2.0
  Using version 0.2.0 (newest of versions: 0.1, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.2.0)
  Created temporary directory: /tmp/pip-unpack-3ldem2ea
  Looking up "https://files.pythonhosted.org/packages/56/dd/a7381f1f7241650700efdf3b10400fc4a8ca0819900549f23c8446cedd9c/py3rcon-0.2.0.tar.gz" in the cache
  Current age based on date: 1223
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 1223
  Using cached https://files.pythonhosted.org/packages/56/dd/a7381f1f7241650700efdf3b10400fc4a8ca0819900549f23c8446cedd9c/py3rcon-0.2.0.tar.gz
  Downloading from URL https://files.pythonhosted.org/packages/56/dd/a7381f1f7241650700efdf3b10400fc4a8ca0819900549f23c8446cedd9c/py3rcon-0.2.0.tar.gz#sha256=6b21e82b2520b4f009c30b0a8e55ef1be71ba52aeaf14ff56b4a85a1c5fb997e (from https://pypi.org/simple/py3rcon/)
  Added py3rcon from https://files.pythonhosted.org/packages/56/dd/a7381f1f7241650700efdf3b10400fc4a8ca0819900549f23c8446cedd9c/py3rcon-0.2.0.tar.gz#sha256=6b21e82b2520b4f009c30b0a8e55ef1be71ba52aeaf14ff56b4a85a1c5fb997e to build tracker '/tmp/pip-req-tracker-6tu2p881'
    Running setup.py (path:/tmp/pip-install-zhwwf4xt/py3rcon/setup.py) egg_info for package py3rcon
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/py3rcon.egg-info
    writing pip-egg-info/py3rcon.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/py3rcon.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/py3rcon.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/py3rcon.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/py3rcon.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/py3rcon.egg-info/SOURCES.txt'
  Source in /tmp/pip-install-zhwwf4xt/py3rcon has version 0.2.0, which satisfies requirement py3rcon from https://files.pythonhosted.org/packages/56/dd/a7381f1f7241650700efdf3b10400fc4a8ca0819900549f23c8446cedd9c/py3rcon-0.2.0.tar.gz#sha256=6b21e82b2520b4f009c30b0a8e55ef1be71ba52aeaf14ff56b4a85a1c5fb997e
  Removed py3rcon from https://files.pythonhosted.org/packages/56/dd/a7381f1f7241650700efdf3b10400fc4a8ca0819900549f23c8446cedd9c/py3rcon-0.2.0.tar.gz#sha256=6b21e82b2520b4f009c30b0a8e55ef1be71ba52aeaf14ff56b4a85a1c5fb997e from build tracker '/tmp/pip-req-tracker-6tu2p881'
Installing collected packages: py3rcon
  Created temporary directory: /tmp/pip-record-uzimwc3v
    Running command /usr/local/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-zhwwf4xt/py3rcon/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-uzimwc3v/install-record.txt --single-version-externally-managed --compile
    running install
    running build
    running build_scripts
    creating build
    creating build/scripts-3.7
    error: file '/tmp/pip-install-zhwwf4xt/py3rcon/py3rcon.py' does not exist
  Running setup.py install for py3rcon ... error
Cleaning up...
  Removing source in /tmp/pip-install-zhwwf4xt/py3rcon
Removed build tracker '/tmp/pip-req-tracker-6tu2p881'
ERROR: Command "/usr/local/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-zhwwf4xt/py3rcon/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-uzimwc3v/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-zhwwf4xt/py3rcon/
Exception information:
Traceback (most recent call last):
  File "/home/stinos/.local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/home/stinos/.local/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 414, in run
    use_user_site=options.use_user_site,
  File "/home/stinos/.local/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
    **kwargs
  File "/home/stinos/.local/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 951, in install
    spinner=spinner,
  File "/home/stinos/.local/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 776, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/usr/local/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-zhwwf4xt/py3rcon/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-uzimwc3v/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-zhwwf4xt/py3rcon/`

**Comment by wmetryka** [comment]
All this time setup.py was missing... 

Fixed.
